version: '3.9'

services:
  postgres:
    image: 'postgres:16.0-alpine'
    container_name: loan-book-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=loan
      - POSTGRES_DB=loan-db
