version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: loan-book-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=example
