spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: loan
    password: example
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

