spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    username: test
#    password: test

#    driver-class-name: org.postgresql.Driver

