spring:
  application:
    name: loan-book

server:
  servlet:
    context-path: /api


jwt:
  secret: secret

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: maindola.amit@gmail.com
  password: your-email-password
  properties:
    mail:
      smtp:
        auth: true
      starttls:
        enable: true