spring:
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: loan
    password: example
    url: jdbc:postgresql://localhost:5433/loan-db
    driver-class-name: org.postgresql.Driver
